### PR TITLE
Changed line 9 to check if the password variable is empty

### PR DESCRIPTION
**Pull request by msbrowning**
Line 9 was checking the positional argument against being empty. Checking if the PASSWORD variable is empty allows you to define a password or generate a random password as intended.

### CODE REVIEW

**Comment by bkonicek** [comment]
In this case there's no difference between using `$3` and `$PASSWORD` - `$PASSWORD` is set to the value of `$3` on line 4, so if one is empty the other is too, so either way will work. Personally, I do prefer using `$PASSWORD` because it makes the code easier to read.

**Comment by msbrowning** [comment]
The code spits out a generated password even when you pass a password as an argument. I've verified that this change fixes that issue using "echo $PASSWORD" after the first if statement. Does your code not have this issue?

**Comment by bkonicek** [comment]
You're totally right, my code was slightly different so it was working for me. I was being lazy and tested against the code I wrote since I didn't have this repo cloned at the time...sorry about that. The full reason `$3` doesn't work is because when you call a function any argument references in the function are local to that function. So another way to fix it would be to pass the original arguments to the `addUser` call on line 48, like `addUser $1 $2 $3`. Then using `$3` will see that the password argument is not empty.

Before the `addUser` and `deleteUser` functions were added this would have worked fine with no changes.

**Comment by msbrowning** [comment]
Good to know a different way to tackle the problem.

**Review by mastermndio — APPROVED** [review]

**Pull request merged**
